spring.application.name=eureka-server

server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true
eureka.server.wait-time-in-ms-when-sync-empty=0

